repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: debug-statements
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-json
      - id: check-toml
      - id: check-symlinks
      - id: name-tests-test
        args:
          - "--pytest-test-first"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "-h"
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-docstring-first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff-format
        files: ^hooks
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.14.1
  #   hooks:
  #     - id: mypy
  #       exclude: ^tests/
  #       args:
  #         [
  #           --strict,
  #           "--disable-error-code",
  #           "type-arg",
  #           "--disable-error-code",
  #           "import-untyped",
  #           "--disable-error-code",
  #           "import-not-found",
  #           "--disable-error-code",
  #           "misc",
  #           "--disable-error-code",
  #           "unused-ignore",
  #           "--disable-error-code",
  #           "no-any-return",
  #         ]
  - repo: https://github.com/thoughtworks/talisman
    rev: "v1.32.0" # Update me!
    hooks:
      # both pre-commit and pre-push supported
      # -   id: talisman-push
      - id: talisman-commit
        entry: cmd --githook pre-commit
  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.18.4
  #   hooks:
  #     - id: gitleaks
