name: flwr-e2g-demo

services:
  # create a SuperLink component
  superlink:
    image: docker.io/flwr/superlink:1.14.0
    ports:
      - "9091:9091"
      - "9092:9092"
    command:
      - --insecure
